class Language {
  final String code;
  final String name;
  final String flagCode;

  const Language({
    required this.code,
    required this.name,
    required this.flagCode,
  });
}

final List<Language> languages = [
  Language(code: 'ar', name: 'Arabic', flagCode: 'ar'),
  Language(code: 'bn', name: 'Bengali', flagCode: 'bn'),
  Language(code: 'zh', name: 'Chinese (Simplified)', flagCode: 'zh'),
  Language(code: 'zh_tw', name: 'Chinese (Traditional)', flagCode: 'tw'),
  Language(code: 'en', name: 'English', flagCode: 'en'),
  Language(code: 'fr', name: 'French', flagCode: 'fr'),
  Language(code: 'de', name: 'German', flagCode: 'de'),
  Language(code: 'hi', name: 'Hindi', flagCode: 'hi'),
  Language(code: 'aa', name: 'Afar', flagCode: 'aa'),
  Language(code: 'ab', name: 'Abkhazian', flagCode: 'ab'),
  Language(code: 'af', name: 'Afrikaans', flagCode: 'af'),
  Language(code: 'ak', name: 'Akan', flagCode: 'ak'),
  Language(code: 'sq', name: 'Albanian', flagCode: 'sq'),
  Language(code: 'am', name: 'Amharic', flagCode: 'am'),
  Language(code: 'an', name: 'Aragonese', flagCode: 'an'),
  Language(code: 'hy', name: 'Armenian', flagCode: 'hy'),
  Language(code: 'as', name: 'Assamese', flagCode: 'as'),
  Language(code: 'ay', name: 'Aymara', flagCode: 'ay'),
  Language(code: 'az', name: 'Azerbaijani', flagCode: 'az'),
  Language(code: 'bm', name: 'Bambara', flagCode: 'bm'),
  Language(code: 'eu', name: 'Basque', flagCode: 'eu'),
  Language(code: 'be', name: 'Belarusian', flagCode: 'be'),
  Language(code: 'bh', name: 'Bihari', flagCode: 'bh'),
  Language(code: 'bi', name: 'Bislama', flagCode: 'bi'),
  Language(code: 'bs', name: 'Bosnian', flagCode: 'bs'),
  Language(code: 'br', name: 'Breton', flagCode: 'br'),
  Language(code: 'bg', name: 'Bulgarian', flagCode: 'bg'),
  Language(code: 'my', name: 'Burmese', flagCode: 'my'),
  Language(code: 'ca', name: 'Catalan', flagCode: 'ca'),
  Language(code: 'ch', name: 'Chamorro', flagCode: 'ch'),
  Language(code: 'ce', name: 'Chechen', flagCode: 'ce'),
  Language(code: 'ny', name: 'Chichewa', flagCode: 'ny'),
  Language(code: 'co', name: 'Corsican', flagCode: 'co'),
  Language(code: 'cr', name: 'Cree', flagCode: 'cr'),
  Language(code: 'hr', name: 'Croatian', flagCode: 'hr'),
  Language(code: 'cs', name: 'Czech', flagCode: 'cs'),
  Language(code: 'da', name: 'Danish', flagCode: 'da'),
  Language(code: 'dv', name: 'Divehi', flagCode: 'dv'),
  Language(code: 'nl', name: 'Dutch', flagCode: 'nl'),
  Language(code: 'et', name: 'Estonian', flagCode: 'et'),
  Language(code: 'ee', name: 'Ewe', flagCode: 'ee'),
  Language(code: 'fo', name: 'Faroese', flagCode: 'fo'),
  Language(code: 'fj', name: 'Fijian', flagCode: 'fj'),
  Language(code: 'fi', name: 'Finnish', flagCode: 'fi'),
  Language(code: 'gl', name: 'Galician', flagCode: 'gl'),
  Language(code: 'ka', name: 'Georgian', flagCode: 'ka'),
  Language(code: 'el', name: 'Greek', flagCode: 'el'),
  Language(code: 'gn', name: 'Guarani', flagCode: 'gn'),
  Language(code: 'gu', name: 'Gujarati', flagCode: 'gu'),
  Language(code: 'ht', name: 'Haitian Creole', flagCode: 'ht'),
  Language(code: 'ha', name: 'Hausa', flagCode: 'ha'),
  Language(code: 'he', name: 'Hebrew', flagCode: 'he'),
  Language(code: 'hu', name: 'Hungarian', flagCode: 'hu'),
  Language(code: 'is', name: 'Icelandic', flagCode: 'is'),
  Language(code: 'id', name: 'Indonesian', flagCode: 'id'),
  Language(code: 'ga', name: 'Irish', flagCode: 'ga'),
  Language(code: 'it', name: 'Italian', flagCode: 'it'),
  Language(code: 'ja', name: 'Japanese', flagCode: 'ja'),
  Language(code: 'jv', name: 'Javanese', flagCode: 'jv'),
  Language(code: 'kn', name: 'Kannada', flagCode: 'kn'),
  Language(code: 'kk', name: 'Kazakh', flagCode: 'kk'),
  Language(code: 'km', name: 'Khmer', flagCode: 'km'),
  Language(code: 'ko', name: 'Korean', flagCode: 'ko'),
  Language(code: 'ku', name: 'Kurdish', flagCode: 'ku'),
  Language(code: 'lo', name: 'Lao', flagCode: 'lo'),
  Language(code: 'la', name: 'Latin', flagCode: 'la'),
  Language(code: 'lv', name: 'Latvian', flagCode: 'lv'),
  Language(code: 'lt', name: 'Lithuanian', flagCode: 'lt'),
  Language(code: 'mk', name: 'Macedonian', flagCode: 'mk'),
  Language(code: 'ms', name: 'Malay', flagCode: 'ms'),
  Language(code: 'ml', name: 'Malayalam', flagCode: 'ml'),
  Language(code: 'mt', name: 'Maltese', flagCode: 'mt'),
  Language(code: 'mi', name: 'Maori', flagCode: 'mi'),
  Language(code: 'mr', name: 'Marathi', flagCode: 'mr'),
  Language(code: 'mn', name: 'Mongolian', flagCode: 'mn'),
  Language(code: 'ne', name: 'Nepali', flagCode: 'ne'),
  Language(code: 'no', name: 'Norwegian', flagCode: 'no'),
  Language(code: 'ps', name: 'Pashto', flagCode: 'ps'),
  Language(code: 'fa', name: 'Persian', flagCode: 'fa'),
  Language(code: 'pl', name: 'Polish', flagCode: 'pl'),
  Language(code: 'pt', name: 'Portuguese', flagCode: 'pt'),
  Language(code: 'pa', name: 'Punjabi', flagCode: 'pa'),
  Language(code: 'qu', name: 'Quechua', flagCode: 'qu'),
  Language(code: 'ro', name: 'Romanian', flagCode: 'ro'),
  Language(code: 'ru', name: 'Russian', flagCode: 'ru'),
  Language(code: 'sm', name: 'Samoan', flagCode: 'sm'),
  Language(code: 'sr', name: 'Serbian', flagCode: 'sr'),
  Language(code: 'sk', name: 'Slovak', flagCode: 'sk'),
  Language(code: 'sl', name: 'Slovenian', flagCode: 'sl'),
  Language(code: 'so', name: 'Somali', flagCode: 'so'),
  Language(code: 'es', name: 'Spanish', flagCode: 'es'),
  Language(code: 'sw', name: 'Swahili', flagCode: 'sw'),
  Language(code: 'sv', name: 'Swedish', flagCode: 'sv'),
  Language(code: 'tl', name: 'Tagalog', flagCode: 'tl'),
  Language(code: 'tg', name: 'Tajik', flagCode: 'tg'),
  Language(code: 'ta', name: 'Tamil', flagCode: 'ta'),
  Language(code: 'te', name: 'Telugu', flagCode: 'te'),
  Language(code: 'th', name: 'Thai', flagCode: 'th'),
  Language(code: 'tr', name: 'Turkish', flagCode: 'tr'),
  Language(code: 'uk', name: 'Ukrainian', flagCode: 'uk'),
  Language(code: 'ur', name: 'Urdu', flagCode: 'ur'),
  Language(code: 'uz', name: 'Uzbek', flagCode: 'uz'),
  Language(code: 'cy', name: 'Welsh', flagCode: 'cy'),
  Language(code: 'xh', name: 'Xhosa', flagCode: 'xh'),
  Language(code: 'zu', name: 'Zulu', flagCode: 'zu'),
];
